// This file is automatically generated and used by ShadCN components to handle className merging.
// It combines `clsx` for conditional class handling and `tailwind-merge` to resolve Tailwind CSS class conflicts.
// Although it might logically belong in the /utils directory, it is placed here because it is generated by ShadCN
// and referenced in its components by default. Moving it requires updating imports in all generated components.

import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
