import type { Metadata } from "next";
import type { SupportedLocale } from "@/types/locales";
import { Geist, Geist_Mono } from "next/font/google";
import { getCurrentThemeAndMode } from "@/utils/theme/theme.server";
import "@/assets/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: SupportedLocale };
}>) {
  const { locale } = await params;
  const { theme, mode } = await getCurrentThemeAndMode();

  return (
    <html lang={locale} className={`${theme} ${mode}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
