import { getThemeClasses } from "@/utils/theme/theme.server";
import "@/assets/styles/globals.css";
import LocaleProvider from "@/components/providers/LocaleProvider";
import TranslateProvider from "@/components/providers/TranslateProvider";
import AuthProvider from "@/components/providers/AuthProvider";
import { auth } from "@/lib/auth";

import type { Metadata } from "next";
import type { SupportedLocale } from "@/types/locales";
import type { User } from "@prisma/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: SupportedLocale };
}>) {
  const { locale } = await params;
  const themeClasses = await getThemeClasses();
  let user;
  const authResult = await auth();

  if (authResult?.user?.email) {
    const { id, email, name, image, roleId } = authResult?.user as User;
    user = { id, email, name, image, roleId };
  }

  return (
    <AuthProvider user={user}>
      <LocaleProvider locale={locale}>
        <TranslateProvider>
          <html lang={locale} className={themeClasses}>
            <body className={"antialiased"}>{children}</body>
          </html>
        </TranslateProvider>
      </LocaleProvider>
    </AuthProvider>
  );
}
