import type { Metadata } from "next";
import type { SupportedLocale } from "@/types/locales";
import { getThemeClasses } from "@/utils/theme/theme.server";
import "@/assets/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: SupportedLocale };
}>) {
  const { locale } = await params;
  const themeClasses = await getThemeClasses();

  return (
    <html lang={locale} className={themeClasses}>
      <body className={"antialiased"}>{children}</body>
    </html>
  );
}
