// This file is automatically generated and used by ShadCN components to handle className merging.
// It combines `clsx` for conditional class handling and `tailwind-merge` to resolve Tailwind CSS class conflicts.

import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
